import Link from "next/link";
import { Clock, Pencil, ArrowRight } from "lucide-react";
import { getAllCards } from "@/lib/data";
import { displayLabel } from "@/lib/types";

export const metadata = {
  title: "更新日志 · 图鉴社",
  description: "图鉴社的内容更新历史 — 收录、修订、勘误。",
};

/**
 * /changelog — site-wide content update log.
 *
 * Aggregates 3 kinds of events:
 *   1. 收录 (card created): all 60 cards' createdAt, since they
 *      were each generated by a wizard / AI run
 *   2. 修订 (content edit): cards with `revisions[]`, newest first
 *   3. 勘误 (errata): a card's own mailto + log-revision path,
 *      surfaced here as a CTA so users know they CAN report
 *      errors (the actual mailto link is on each card's detail
 *      page)
 *
 * Output is reverse-chronological, deduped by date+slug+summary
 * so the same revision isn't counted twice if it touched multiple
 * fields.
 */
type ChangelogEntry = {
  date: Date;
  type: "created" | "revised";
  slug: string;
  title: string;
  summary: string;
  fields?: string[];
};

function getAllEntries(): ChangelogEntry[] {
  const cards = getAllCards();
  const entries: ChangelogEntry[] = [];

  for (const c of cards) {
    entries.push({
      date: new Date(c.createdAt),
      type: "created",
      slug: c.slug,
      title: c.title,
      summary: `收录「${c.title}」到图鉴社 (${displayLabel(c.kind)} · No.${c.seriesNo})`,
    });
    if (c.revisions) {
      for (const r of c.revisions) {
        entries.push({
          date: new Date(r.date),
          type: "revised",
          slug: c.slug,
          title: c.title,
          summary: r.summary,
          fields: r.fields,
        });
      }
    }
  }

  // Newest first
  entries.sort((a, b) => b.date.getTime() - a.date.getTime());
  return entries;
}

export default function ChangelogPage() {
  const entries = getAllEntries();

  // Group by YYYY-MM in Asia/Shanghai (Round 12 fix — `toISOString()` is
  // UTC, so entries created near midnight BJT would file into the wrong
  // month group and show the wrong date to Chinese users).
  const shanghaiFmt = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Shanghai",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
  const groups = new Map<string, ChangelogEntry[]>();
  for (const e of entries) {
    // en-CA emits YYYY-MM-DD, slice(0, 7) gives YYYY-MM
    const ym = shanghaiFmt.format(e.date).slice(0, 7);
    if (!groups.has(ym)) groups.set(ym, []);
    groups.get(ym)!.push(e);
  }

  return (
    <div className="container py-12 md:py-16">
      <header className="mb-12 max-w-2xl">
        <div className="flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-gold-deep mb-3">
          <Clock className="h-3.5 w-3.5" aria-hidden="true" />
          <span>更新日志</span>
        </div>
        <h1 className="font-serif text-3xl md:text-4xl font-bold mb-3">
          内容更新记录
        </h1>
        <p className="text-muted-foreground leading-relaxed">
          收录 {entries.filter((e) => e.type === "created").length} 张图鉴,
          修订 {entries.filter((e) => e.type === "revised").length} 条。
          发现错误?{" "}
          <Link
            href="/about"
            className="text-gold-deep hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 rounded-sm"
          >
            告诉我们
          </Link>
          , 每个图鉴页底部都有「勘误」入口。
        </p>
      </header>

      <div className="relative">
        {/* Vertical rail (desktop only) */}
        <div
          aria-hidden="true"
          className="hidden md:block absolute top-0 bottom-0 left-[7.25rem] w-px bg-gradient-to-b from-border via-border to-transparent"
        />

        <ol className="space-y-12 list-none p-0">
          {[...groups.entries()].map(([month, items]) => {
            const [y, m] = month.split("-");
            const label = `${y} 年 ${parseInt(m, 10)} 月`;
            return (
              <li key={month}>
                <div className="md:flex md:items-baseline md:gap-8 mb-6">
                  <h2 className="font-serif text-2xl md:text-3xl font-bold text-gold-deep md:min-w-[6.5rem] md:text-right tabular-nums">
                    {label}
                  </h2>
                  <p className="text-xs text-muted-foreground mt-1 md:mt-0 tabular-nums">
                    {items.length} 条更新
                  </p>
                </div>

                <ul className="space-y-3 md:space-y-4 md:pl-[8.5rem] list-none p-0">
                  {items.map((entry, i) => (
                    <li key={`${entry.slug}-${entry.type}-${i}`} className="relative">
                      <span
                        aria-hidden="true"
                        className="hidden md:block absolute -left-[1.7rem] top-3 h-3 w-3 rounded-full bg-gold-deep ring-4 ring-background"
                      />
                      <Link
                        href={`/cards/${entry.slug}`}
                        className="group block rounded-lg border border-border bg-card p-4 hover:border-gold hover:shadow-card transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
                      >
                        <div className="flex items-start gap-3">
                          <div className="mt-0.5 shrink-0">
                            {entry.type === "revised" ? (
                              <Pencil className="h-4 w-4 text-gold-deep" aria-hidden="true" />
                            ) : (
                              <Clock className="h-4 w-4 text-muted-foreground" aria-hidden="true" />
                            )}
                          </div>
                          <div className="min-w-0 flex-1">
                            <div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.2em] text-muted-foreground/70 mb-1">
                          <span className="font-medium text-foreground/80 tabular-nums">
                            {shanghaiFmt.format(entry.date)}
                          </span>
                          <span>·</span>
                          <span>
                            {entry.type === "revised" ? "修订" : "收录"}
                          </span>
                        </div>
                            <p className="font-serif text-sm font-medium leading-snug group-hover:text-gold-deep transition-colors">
                              {entry.summary}
                            </p>
                            {entry.fields && entry.fields.length > 0 && (
                              <p className="mt-1.5 text-[10px] uppercase tracking-[0.15em] text-muted-foreground/70">
                                [{entry.fields.join(", ")}]
                              </p>
                            )}
                          </div>
                          <ArrowRight className="h-4 w-4 text-muted-foreground/50 group-hover:text-gold-deep group-hover:translate-x-0.5 transition-all shrink-0 mt-0.5" aria-hidden="true" />
                        </div>
                      </Link>
                    </li>
                  ))}
                </ul>
              </li>
            );
          })}
        </ol>
      </div>
    </div>
  );
}
