import Link from "next/link";
import { Clock, Pencil, ArrowRight, Sparkles } from "lucide-react";
import { getAllCards } from "@/lib/data";
import { displayLabel } from "@/lib/types";
import { cn } from "@/lib/utils";

export const metadata = {
  title: "更新日志 · 图鉴社",
  description: "图鉴社的内容更新历史 — 收录、修订、里程碑。",
};

/**
 * /changelog — site-wide content update log.
 *
 * Aggregates 3 kinds of events:
 *   1. 收录 (card created): all 60 cards' createdAt, since they
 *      were each generated by a wizard / AI run
 *   2. 修订 (content edit): cards with `revisions[]`, newest first
 *   3. 里程碑 (site milestone): hand-curated site-wide events
 *      that aren't tied to a single card — MVP launch, scale-up
 *      to 60, design reviews, roadmap completions. Hardcoded in
 *      SITE_MILESTONES below; pure data, not auto-derived.
 *
 * Output is reverse-chronological, deduped by date+slug+summary
 * so the same revision isn't counted twice if it touched multiple
 * fields.
 */
type ChangelogEntry = {
  date: Date;
  type: "created" | "revised" | "milestone";
  slug: string;
  title: string;
  summary: string;
  fields?: string[];
};

/**
 * Site-wide milestone events. Round 15 added these so /changelog
 * tells the project's story (5 days from MVP to polished atlas)
 * not just the per-card churn.
 *
 * `slug` is a stable identifier (used as React key); it doesn't
 * correspond to a real card — milestones link to /about instead.
 */
const SITE_MILESTONES: Array<Omit<ChangelogEntry, "date"> & { date: string }> = [
  {
    date: "2026-06-12",
    type: "milestone",
    slug: "milestone-mvp",
    title: "MVP 上线",
    summary: "图鉴社 Atlas Kit 首版上线: 首页、图鉴详情、3 个系列占位骨架、基础主题切换。",
  },
  {
    date: "2026-06-13",
    type: "milestone",
    slug: "milestone-60-cards",
    title: "图鉴扩到 60 张",
    summary: "12 类型 × 5 张 全量铺开, 启用三层图像 (thumb 384w · card 600w · full 1024w) 优化首屏。",
  },
  {
    date: "2026-06-14",
    type: "milestone",
    slug: "milestone-design-review",
    title: "首轮设计 review",
    summary: "design-taste-frontend skill 全站 audit, 12 项修复 (色板 / 排版 / 间距 / 微文案) 一次性落地。",
  },
  {
    date: "2026-06-16",
    type: "milestone",
    slug: "milestone-roadmap",
    title: "百科化升级 (6 项 roadmap 完成)",
    summary: "知识图谱 + 历史沿革 + 地图 + 修订勘误 + 探索路由 + 参考来源, 从「图鉴集」升级为「中文百科」。",
  },
  {
    date: "2026-06-16",
    type: "milestone",
    slug: "milestone-polish",
    title: "连续 4 轮设计 audit",
    summary: "Round 8 + 9 + 12 + 13 + 14, 累计 30+ 项 polish, 站点整体评分从「有想法的草稿」拉到「可以发布」。",
  },
];

function getAllEntries(): ChangelogEntry[] {
  const cards = getAllCards();
  const entries: ChangelogEntry[] = [];

  for (const c of cards) {
    entries.push({
      date: new Date(c.createdAt),
      type: "created",
      slug: c.slug,
      title: c.title,
      summary: `收录「${c.title}」到图鉴社 (${displayLabel(c.kind)} · No.${c.seriesNo})`,
    });
    if (c.revisions) {
      for (const r of c.revisions) {
        entries.push({
          date: new Date(r.date),
          type: "revised",
          slug: c.slug,
          title: c.title,
          summary: r.summary,
          fields: r.fields,
        });
      }
    }
  }

  // Inject site-wide milestones (Round 15)
  for (const m of SITE_MILESTONES) {
    entries.push({
      date: new Date(m.date),
      type: "milestone",
      slug: m.slug,
      title: m.title,
      summary: m.summary,
    });
  }

  // Newest first
  entries.sort((a, b) => b.date.getTime() - a.date.getTime());
  return entries;
}

export default function ChangelogPage() {
  const entries = getAllEntries();

  // Group by YYYY-MM in Asia/Shanghai (Round 12 fix — `toISOString()` is
  // UTC, so entries created near midnight BJT would file into the wrong
  // month group and show the wrong date to Chinese users).
  const shanghaiFmt = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Shanghai",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
  const groups = new Map<string, ChangelogEntry[]>();
  for (const e of entries) {
    // en-CA emits YYYY-MM-DD, slice(0, 7) gives YYYY-MM
    const ym = shanghaiFmt.format(e.date).slice(0, 7);
    if (!groups.has(ym)) groups.set(ym, []);
    groups.get(ym)!.push(e);
  }

  return (
    <div className="container py-12 md:py-16">
      <header className="mb-12 max-w-2xl">
        <div className="flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-gold-deep mb-3">
          <Clock className="h-3.5 w-3.5" aria-hidden="true" />
          <span>更新日志</span>
        </div>
        <h1 className="font-serif text-3xl md:text-4xl font-bold mb-3">
          内容更新记录
        </h1>
        <p className="text-muted-foreground leading-relaxed">
          收录 {entries.filter((e) => e.type === "created").length} 张图鉴,
          修订 {entries.filter((e) => e.type === "revised").length} 条,
          站点里程碑 {entries.filter((e) => e.type === "milestone").length} 项。
          发现错误?{" "}
          <Link
            href="/about"
            className="text-gold-deep hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 rounded-sm"
          >
            告诉我们
          </Link>
          , 每个图鉴页底部都有「勘误」入口。
        </p>
      </header>

      <div className="relative">
        {/* Vertical rail (desktop only) */}
        <div
          aria-hidden="true"
          className="hidden md:block absolute top-0 bottom-0 left-[7.25rem] w-px bg-gradient-to-b from-border via-border to-transparent"
        />

        <ol className="space-y-12 list-none p-0">
          {[...groups.entries()].map(([month, items]) => {
            const [y, m] = month.split("-");
            const label = `${y} 年 ${parseInt(m, 10)} 月`;
            return (
              <li key={month}>
                <div className="md:flex md:items-baseline md:gap-8 mb-6">
                  <h2 className="font-serif text-2xl md:text-3xl font-bold text-gold-deep md:min-w-[6.5rem] md:text-right tabular-nums">
                    {label}
                  </h2>
                  <p className="text-xs text-muted-foreground mt-1 md:mt-0 tabular-nums">
                    {items.length} 条更新
                  </p>
                </div>

                <ul className="space-y-3 md:space-y-4 md:pl-[8.5rem] list-none p-0">
                  {items.map((entry, i) => {
                    const isMilestone = entry.type === "milestone";
                    return (
                      <li key={`${entry.slug}-${entry.type}-${i}`} className="relative">
                        <span
                          aria-hidden="true"
                          className={cn(
                            "hidden md:block absolute -left-[1.7rem] top-3 h-3 w-3 rounded-full ring-4 ring-background",
                            isMilestone ? "bg-gold-deep ring-gold/30" : "bg-gold-deep",
                          )}
                        />
                        <Link
                          // Milestones link to /about since the slug is
                          // synthetic (no card behind it). Card events
                          // link to the card detail.
                          href={isMilestone ? "/about" : `/cards/${entry.slug}`}
                          className={cn(
                            "group block rounded-lg border bg-card p-4 hover:border-gold hover:shadow-card transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
                            // Milestone gets a slightly elevated look so it
                            // stands out from the dense list of card events.
                            isMilestone
                              ? "border-gold/40 bg-gradient-to-br from-cream to-card"
                              : "border-border",
                          )}
                        >
                          <div className="flex items-start gap-3">
                            <div className="mt-0.5 shrink-0">
                              {entry.type === "milestone" ? (
                                <Sparkles className="h-4 w-4 text-gold-deep" aria-hidden="true" />
                              ) : entry.type === "revised" ? (
                                <Pencil className="h-4 w-4 text-gold-deep" aria-hidden="true" />
                              ) : (
                                <Clock className="h-4 w-4 text-muted-foreground" aria-hidden="true" />
                              )}
                            </div>
                            <div className="min-w-0 flex-1">
                              <div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.2em] text-muted-foreground/70 mb-1">
                                <span className="font-medium text-foreground/80 tabular-nums">
                                  {shanghaiFmt.format(entry.date)}
                                </span>
                                <span>·</span>
                                <span>
                                  {entry.type === "milestone"
                                    ? "里程碑"
                                    : entry.type === "revised"
                                      ? "修订"
                                      : "收录"}
                                </span>
                                {isMilestone && (
                                  <span className="font-serif text-sm font-semibold text-gold-deep normal-case tracking-normal ml-1">
                                    {entry.title}
                                  </span>
                                )}
                              </div>
                              <p className={cn(
                                "font-serif leading-snug group-hover:text-gold-deep transition-colors",
                                isMilestone ? "text-sm" : "text-sm font-medium",
                              )}>
                                {entry.summary}
                              </p>
                              {entry.fields && entry.fields.length > 0 && (
                                <p className="mt-1.5 text-[10px] uppercase tracking-[0.15em] text-muted-foreground/70">
                                  [{entry.fields.join(", ")}]
                                </p>
                              )}
                            </div>
                            <ArrowRight className="h-4 w-4 text-muted-foreground/50 group-hover:text-gold-deep group-hover:translate-x-0.5 transition-all shrink-0 mt-0.5" aria-hidden="true" />
                          </div>
                        </Link>
                      </li>
                    );
                  })}
                </ul>
              </li>
            );
          })}
        </ol>
      </div>
    </div>
  );
}
