import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { ThemeProvider } from "@/components/theme-provider";
import { WebVitals } from "@/components/web-vitals";
import { SwRegister } from "@/components/sw-register";
import { KeyboardShortcuts } from "@/components/keyboard-shortcuts";

// Local fonts only — no Google Fonts URL.
// Fonts checked into src/app/fonts/ (committed to git). On Windows the
// source-of-truth is C:\Windows\Fonts; on macOS / Linux you can grab
// the same files from Google Fonts (Noto Sans/Serif SC Variable Fonts,
// OFL licensed). The two extra woff files (Geist Mono / Geist) are
// the dev-mode fallback monospace.
// Noto Sans SC (sans) + Noto Serif SC (serif) — both are Variable Fonts so
// one file covers all weights (100-900).
const notoSansSC = localFont({
  src: "./fonts/NotoSansSC-VF.ttf",
  variable: "--font-sans",
  display: "swap",
  weight: "100 900",
  fallback: [
    '"PingFang SC"',
    '"Microsoft YaHei"',
    '"Helvetica Neue"',
    "system-ui",
    "sans-serif",
  ],
});

const notoSerifSC = localFont({
  src: "./fonts/NotoSerifSC-VF.ttf",
  variable: "--font-serif",
  display: "swap",
  weight: "100 900",
  fallback: [
    '"Songti SC"',
    '"Source Han Serif SC"',
    '"Noto Serif CJK SC"',
    "Georgia",
    "serif",
  ],
});

export const metadata: Metadata = {
  title: "图鉴社 · Atlas Kit — 系列化中文科普图鉴",
  description: "高质量、可系列化的中文科普图鉴卡片集。浏览、收藏、并通过 AI 一键生成你自己的图鉴。",
  metadataBase: new URL(process.env.SITE_URL ?? "http://localhost:3000"),
  openGraph: {
    title: "图鉴社 · Atlas Kit",
    description: "系列化中文科普图鉴卡片集 · 博物馆质感 · AI 一键生成",
    type: "website",
    locale: "zh_CN",
    // images auto-resolved from /opengraph-image.tsx (1200x630)
    // Dev quirk: the edge runtime can fail in 'next dev' mode; works
    // in 'next build' + 'next start' (production). See AGENTS.md.
  },
  twitter: {
    card: "summary_large_image",
    title: "图鉴社 · Atlas Kit",
    description: "系列化中文科普图鉴卡片集",
    // Explicit so crawlers don't depend on Next 14's default fallback
    // to the openGraph images array. Both point to the same dynamic
    // route generated by src/app/opengraph-image.tsx.
    images: ["/opengraph-image"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="zh-CN"
      suppressHydrationWarning
      className={`${notoSansSC.variable} ${notoSerifSC.variable}`}
    >
      <head>
        {/* Preconnect to the matrix CDN so AI-generated images start
            downloading in parallel with the HTML body. Best-effort: misses
            are silent and cost nothing. */}
        <link rel="preconnect" href="https://cdn.minimaxi.com" crossOrigin="anonymous" />
        {/* theme-color: matches brand cream so Safari/Chrome mobile chrome
            blends instead of having a stark white bar. */}
        <meta name="theme-color" content="#f7f2e8" media="(prefers-color-scheme: light)" />
        <meta name="theme-color" content="#1a1814" media="(prefers-color-scheme: dark)" />
        {/* R40 (2026-06-21): PWA manifest + apple-touch-icon. Lets the
            site be installed as a standalone app on mobile (Android
            shows install banner; iOS allows Add to Home Screen). */}
        <link rel="manifest" href="/manifest.webmanifest" />
        <link rel="apple-touch-icon" href="/icon-192.png" />
        {/* Schema.org site-level JSON-LD — Organization + WebSite
            (with SearchAction) is what Google uses for the brand
            panel + sitelinks search box. Rendered once at root
            so every page inherits. The home page Article is in
            app/page.tsx separately. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "图鉴社 Atlas Kit",
              alternateName: "Atlas Kit · 图鉴社",
              url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://atlas-kit-six.vercel.app",
              logo: {
                "@type": "ImageObject",
                url: `${process.env.NEXT_PUBLIC_SITE_URL ?? "https://atlas-kit-six.vercel.app"}/icon-512.png`,
                width: 512,
                height: 512,
              },
              description: "系列化中文科普图鉴卡片集 · 博物馆质感 · AI 一键生成",
              foundingDate: "2026",
              inLanguage: "zh-CN",
              sameAs: [
                "https://github.com/mishishi/atlas-kit",
              ],
            }),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              name: "图鉴社 Atlas Kit",
              url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://atlas-kit-six.vercel.app",
              inLanguage: "zh-CN",
              publisher: {
                "@type": "Organization",
                name: "图鉴社 Atlas Kit",
              },
              potentialAction: {
                "@type": "SearchAction",
                target: {
                  "@type": "EntryPoint",
                  urlTemplate: `${process.env.NEXT_PUBLIC_SITE_URL ?? "https://atlas-kit-six.vercel.app"}/search?q={search_term_string}`,
                },
                // Schema.org SearchAction requires a query-input.
                // We use the URL fragment-in-search pattern Google uses.
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />
        {/* Theme bootstrap — runs synchronously in <head> BEFORE React
            paints, so users with stored "light"/"dark" never see a
            light→dark or dark→light flash. Mirrors the next-themes
            inline-script pattern. Reads from localStorage "theme"
            (the key ThemeProvider writes in src/components/theme-provider.tsx);
            falls back to prefers-color-scheme for "system".
            Idempotent: re-applies on every load. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');var d=t==='dark'||((t==='system'||!t)&&window.matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.classList.toggle('dark',d);}catch(e){}})();`,
          }}
        />
      </head>
      <body className="min-h-dvh antialiased font-sans">
        <ThemeProvider defaultTheme="light">
          <div className="flex min-h-dvh flex-col">
            <SiteHeader />
            <main id="main" className="flex-1" tabIndex={-1}>{children}</main>
            <SiteFooter />
          </div>
        </ThemeProvider>
        {/* R37 Plan B (2026-06-18): Vercel Analytics. 0-config, just
            need the env. Gives us: page views, top routes, real-user
            perf metrics. PM Take 1: ship fast, but you can't ship
            fast without measuring. */}
        <Analytics />
        {/* Toast notifications — inherits theme from <html class="dark"> via sonner theme="system" */}
        <Toaster
          position="bottom-center"
          theme="system"
          richColors
          closeButton
          toastOptions={{
            classNames: {
              toast: "font-sans",
              title: "font-serif",
            },
          }}
        />
        <WebVitals />
        <SwRegister />
        <KeyboardShortcuts />
      </body>
    </html>
  );
}

